// Hashes of prebuilt ghostty-vt binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

const String prebuiltReleaseRepository = 'leynier/dart_terminal';

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'ghostty_vte-v0.1.4';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'vte-linux-x64.tar.gz',
    hash: 'b2ec625532caf52133eeaa615b379bb7ef8c63bd2475e2d450a1539cc783e492',
  ),
  'linux-arm64': AssetHash(
    tarball: 'vte-linux-arm64.tar.gz',
    hash: 'b6c1b3067a8a47161775fcdb596ad392c07dfc063d03e87f3e2d27bca44f023d',
  ),
  'macos-arm64': AssetHash(
    tarball: 'vte-macos-arm64.tar.gz',
    hash: '76707f5febdccf55e9c15e27494ea4aff581762aeeae2b6c68dccd1d85f8df86',
  ),
  'macos-x64': AssetHash(
    tarball: 'vte-macos-x64.tar.gz',
    hash: 'e68859cdc882d672e8ad6b3bc56d193a3f9f0d98bae6dc7783273626e117da08',
  ),
  'windows-x64': AssetHash(
    tarball: 'vte-windows-x64.tar.gz',
    hash: 'af7accf4ed571967068ebb57884f06cf8734b49469335ae1c68bd7ec8cf46374',
  ),
  'windows-arm64': AssetHash(
    tarball: 'vte-windows-arm64.tar.gz',
    hash: '5333a38bd59c5636f518700246d9e46576ab6e1143bff1c4beda85916f04735f',
  ),
  'android-arm64': AssetHash(
    tarball: 'vte-android-arm64.tar.gz',
    hash: '921eb156f01c83087a0005cc873f03506b2b7a9acd9cf29951439783a37dd715',
  ),
  'android-arm': AssetHash(
    tarball: 'vte-android-arm.tar.gz',
    hash: '428ff567616c22e544a290e256782ef0126e32504e44b87f99d31b7f2bd287e0',
  ),
  'android-x64': AssetHash(
    tarball: 'vte-android-x64.tar.gz',
    hash: '9b96282d8d24e993164f530682b8435b39743effede1319cac965f05f4fb0571',
  ),
  'ios-arm64': AssetHash(
    tarball: 'vte-ios-arm64.tar.gz',
    hash: '33caa6fbca903a2d80b5abadfb523dbf7478ec0a79b5939671bea282df61fc27',
  ),
  'ios-sim-arm64': AssetHash(
    tarball: 'vte-ios-sim-arm64.tar.gz',
    hash: 'eecf951716a891a4460838ffa00b9ce5b4956a597bd49a0fdcce2b7f152483f8',
  ),
  'ios-sim-x64': AssetHash(
    tarball: 'vte-ios-sim-x64.tar.gz',
    hash: '89d12dc9fbbd1ad1c4e5bf64f2c24374d7653b6c9778c1ed66cc914c36abe912',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "vte-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
