// Hashes of prebuilt ghostty-vt binaries for each platform.
// Used by the build hook to verify downloaded artifacts.
//
// Generated by tool/write_asset_hashes.dart

// dart format off

const String prebuiltReleaseRepository = 'leynier/dart_terminal';

/// The GitHub release tag from which prebuilt binaries are downloaded.
const String releaseTag = 'ghostty_vte-v0.1.5';

/// Maps platform labels to artifact info and SHA256 hashes.
const Map<String, AssetHash> assetHashes = {
  'linux-x64': AssetHash(
    tarball: 'vte-linux-x64.tar.gz',
    hash: '059d48fe356f1c875aaeff516854e034140080cc4128f4f1a9b8cc9a69b76555',
  ),
  'linux-arm64': AssetHash(
    tarball: 'vte-linux-arm64.tar.gz',
    hash: 'd0519a457793f0b97028c702eb897ceae6afd25f1d8c3c4262cac4dea3be6556',
  ),
  'macos-arm64': AssetHash(
    tarball: 'vte-macos-arm64.tar.gz',
    hash: '958631a633d30b8460ab593ea0a6091fd1f4c7e75f901c38eb2f4b98c4ab4974',
  ),
  'macos-x64': AssetHash(
    tarball: 'vte-macos-x64.tar.gz',
    hash: '827e0fd535394e4fb38906e4002b98696e9d29ff39e0cb71de5572aeb057d787',
  ),
  'windows-x64': AssetHash(
    tarball: 'vte-windows-x64.tar.gz',
    hash: 'b0609ddf0b15fb63ff0f8c1dd304333674f40531811e1becf635a14de4705f9b',
  ),
  'windows-arm64': AssetHash(
    tarball: 'vte-windows-arm64.tar.gz',
    hash: 'c70ef5f6d8ae978b0b704193bf3ce58891ecbeebff1414986ee005d093b923a9',
  ),
  'android-arm64': AssetHash(
    tarball: 'vte-android-arm64.tar.gz',
    hash: '1a0971e651e11f38af92244ca2ed031d9b793b602f1c54df1099f9603e0ac0f7',
  ),
  'android-arm': AssetHash(
    tarball: 'vte-android-arm.tar.gz',
    hash: '9f3488f435c77db67655ba10f4f721bc674155387abe043ec29b27a48b254a12',
  ),
  'android-x64': AssetHash(
    tarball: 'vte-android-x64.tar.gz',
    hash: 'bd302f03bf67bd0b5f186c57074c80c7d4a90895db64a077437f482b8763d658',
  ),
  'ios-arm64': AssetHash(
    tarball: 'vte-ios-arm64.tar.gz',
    hash: '8edcd7bf3601947ebe3c14ec86d575db5405fa89bf6f137e1139bbf188d23bb6',
  ),
  'ios-sim-arm64': AssetHash(
    tarball: 'vte-ios-sim-arm64.tar.gz',
    hash: '882aff4f5174db0d30fddf302a28a592636be794d19b2e58d826af5b9dd11d7f',
  ),
  'ios-sim-x64': AssetHash(
    tarball: 'vte-ios-sim-x64.tar.gz',
    hash: '585663e0cd7b0cac3d6b863cad11984569c46d103de3f5bb1956ec7f2fc6a560',
  ),
};

/// Describes a prebuilt artifact with its download filename and integrity hash.
class AssetHash {
  /// The tarball filename in the GitHub release (e.g. "vte-linux-x64.tar.gz").
  final String tarball;

  /// SHA256 hash of the extracted library file.
  final String hash;

  const AssetHash({required this.tarball, required this.hash});
}
